import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const intern = Inter({
  variable: "--font-intern",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${intern.variable}  antialiased`}>{children}</body>
    </html>
  );
}
